// Package ilp handles MPS/LP file generation and external solver invocation
// for the MtxILP algorithm. It replaces PuLP + CBC from the Python implementation.
//
// To add a new solver, implement the Solver interface and register it in Solve().
package ilp

import (
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"github.com/Vaivaswat2244/OptiFuse_go/services/optimizer/internal/domain"
)

// Result is the output of the ILP solver.
type Result struct {
	Optimal bool
	Status  string
	Groups  [][]*domain.LambdaFunction
}

// Solve formulates the MtxILP problem for the given application,
// writes an MPS file, invokes glpsol (or cbc), parses the solution,
// and returns the resulting partition.
//
// This is a direct translation of the PuLP model in optimal.py.
func Solve(app *domain.Application) (*Result, error) {
	fm := app.FunctionsMap()
	funcs := app.Functions
	critPath := app.CriticalPath()

	// ── Variable naming ───────────────────────────────────────────────────────
	// x[b,f] = 1 if function f is assigned to group rooted at b
	// is_cut[u,v] = 1 if edge (u→v) is a cut (u and v in different groups)
	//
	// Python: x = pulp.LpVariable.dicts("x", ((b.id, f.id) for b in roots for f in app.functions))
	//         is_cut = pulp.LpVariable.dicts("is_cut", ((e[0].id, e[1].id) for e in all_edges))

	xVar := func(bID, fID string) string {
		return fmt.Sprintf("x_%s_%s", sanitize(bID), sanitize(fID))
	}
	cutVar := func(uID, vID string) string {
		return fmt.Sprintf("cut_%s_%s", sanitize(uID), sanitize(vID))
	}

	// Collect all directed edges.
	type dirEdge struct{ u, v *domain.LambdaFunction }
	var edges []dirEdge
	for _, u := range funcs {
		for _, v := range u.Children {
			edges = append(edges, dirEdge{u, v})
		}
	}

	// ── Build LP in free MPS-like format using GLPK LP format ────────────────
	// We use GLPK's LP format (simpler than MPS for hand-generation).
	var sb strings.Builder

	// Objective: minimize data transfer cost on cut edges
	// Python: prob += lpSum(u.get_data_transfer_cost(v.id) * is_cut[u.id, v.id] for u, v in all_edges)
	sb.WriteString("/* OptiFuse MtxILP — generated by ilp.Solve() */\n")
	sb.WriteString("min: ")
	terms := make([]string, 0, len(edges))
	for _, e := range edges {
		cost := e.u.DataTransferCostUSD(e.v.ID)
		if cost > 0 {
			terms = append(terms, fmt.Sprintf("%.10f %s", cost, cutVar(e.u.ID, e.v.ID)))
		}
	}
	if len(terms) == 0 {
		terms = []string{"0"}
	}
	sb.WriteString(strings.Join(terms, " + "))
	sb.WriteString(";\n\n")

	sb.WriteString("/* Constraints */\n\n")

	// 1. Each function assigned to exactly one group root.
	// Python: for f in app.functions: prob += lpSum(x[b.id, f.id] for b in roots) == 1
	for _, f := range funcs {
		parts := make([]string, 0, len(funcs))
		for _, b := range funcs {
			parts = append(parts, xVar(b.ID, f.ID))
		}
		sb.WriteString(fmt.Sprintf("assign_%s: %s = 1;\n", sanitize(f.ID), strings.Join(parts, " + ")))
	}
	sb.WriteString("\n")

	// 2. Root integrity: x[b,f] ≤ x[b,b]
	// Python: for b in roots: for f in app.functions: prob += x[b.id, f.id] <= x[b.id, b.id]
	for _, b := range funcs {
		for _, f := range funcs {
			sb.WriteString(fmt.Sprintf(
				"root_%s_%s: %s - %s <= 0;\n",
				sanitize(b.ID), sanitize(f.ID),
				xVar(b.ID, f.ID), xVar(b.ID, b.ID),
			))
		}
	}
	sb.WriteString("\n")

	// 3. Memory constraint per group.
	// Python: prob += lpSum(f.memory * x[b.id, f.id] for f in app.functions) <= max_memory * x[b.id, b.id]
	for _, b := range funcs {
		memTerms := make([]string, 0, len(funcs))
		for _, f := range funcs {
			memTerms = append(memTerms, fmt.Sprintf("%d %s", f.MemoryMB, xVar(b.ID, f.ID)))
		}
		sb.WriteString(fmt.Sprintf(
			"mem_%s: %s - %d %s <= 0;\n",
			sanitize(b.ID),
			strings.Join(memTerms, " + "),
			app.MaxMemoryMB,
			xVar(b.ID, b.ID),
		))
	}
	sb.WriteString("\n")

	// 4. Cut definition: is_cut[u,v] ≥ x[b,u] - x[b,v] and ≥ x[b,v] - x[b,u]
	// Python: for u, v in all_edges: for b in roots:
	//             prob += is_cut[u,v] >= x[b,u] - x[b,v]
	//             prob += is_cut[u,v] >= x[b,v] - x[b,u]
	for _, e := range edges {
		cv := cutVar(e.u.ID, e.v.ID)
		for _, b := range funcs {
			sb.WriteString(fmt.Sprintf(
				"cutA_%s_%s_%s: %s - %s + %s >= 0;\n",
				sanitize(b.ID), sanitize(e.u.ID), sanitize(e.v.ID),
				cv, xVar(b.ID, e.u.ID), xVar(b.ID, e.v.ID),
			))
			sb.WriteString(fmt.Sprintf(
				"cutB_%s_%s_%s: %s + %s - %s >= 0;\n",
				sanitize(b.ID), sanitize(e.u.ID), sanitize(e.v.ID),
				cv, xVar(b.ID, e.u.ID), xVar(b.ID, e.v.ID),
			))
		}
	}
	sb.WriteString("\n")

	// 5. Latency constraint on critical path.
	// Python: prob += runtime_sum + lpSum(hop_delay * is_cut[u,v] for cp_edges) <= max_latency
	runtimeSum := 0
	for _, f := range critPath {
		runtimeSum += f.RuntimeMs()
	}
	hopTerms := make([]string, 0)
	for i := 0; i < len(critPath)-1; i++ {
		u, v := critPath[i], critPath[i+1]
		hopTerms = append(hopTerms, fmt.Sprintf("%d %s", app.NetworkHopMS, cutVar(u.ID, v.ID)))
	}
	if len(hopTerms) > 0 {
		sb.WriteString(fmt.Sprintf(
			"latency: %s <= %d;\n\n",
			strings.Join(hopTerms, " + "),
			app.MaxLatencyMS-runtimeSum,
		))
	}

	// Binary variable declarations.
	sb.WriteString("bin\n")
	for _, b := range funcs {
		for _, f := range funcs {
			sb.WriteString(fmt.Sprintf("  %s\n", xVar(b.ID, f.ID)))
		}
	}
	for _, e := range edges {
		sb.WriteString(fmt.Sprintf("  %s\n", cutVar(e.u.ID, e.v.ID)))
	}
	sb.WriteString("end\n")

	// ── Write to temp file and invoke solver ──────────────────────────────────
	lpFile, err := os.CreateTemp("", "optifuse_*.lp")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp LP file: %w", err)
	}
	defer os.Remove(lpFile.Name())

	if _, err := lpFile.WriteString(sb.String()); err != nil {
		return nil, fmt.Errorf("failed to write LP file: %w", err)
	}
	lpFile.Close()

	solFile := lpFile.Name() + ".sol"
	defer os.Remove(solFile)

	// Try glpsol first, fall back to cbc.
	var out []byte
	if _, err := exec.LookPath("glpsol"); err == nil {
		out, err = exec.Command("glpsol", "--lp", lpFile.Name(), "-o", solFile, "--tmlim", "60").CombinedOutput()
		if err != nil {
			return &Result{Status: fmt.Sprintf("glpsol error: %s\n%s", err, out)}, nil
		}
	} else {
		out, err = exec.Command("cbc", lpFile.Name(), "solve", "solution", solFile).CombinedOutput()
		if err != nil {
			return &Result{Status: fmt.Sprintf("cbc error: %s\n%s", err, out)}, nil
		}
	}

	// ── Parse solution ────────────────────────────────────────────────────────
	solBytes, err := os.ReadFile(solFile)
	if err != nil {
		return nil, fmt.Errorf("failed to read solution file: %w", err)
	}
	solText := string(solBytes)

	if !strings.Contains(solText, "OPTIMAL") && !strings.Contains(solText, "INTEGER OPTIMAL") {
		return &Result{Status: "infeasible or solver did not find optimal"}, nil
	}

	// Extract x variable values from solution.
	// Build groups: for each b where x[b,b]=1, collect all f where x[b,f]=1.
	groupsMap := make(map[string][]string) // barrierID → []memberID
	for _, line := range strings.Split(solText, "\n") {
		for _, b := range funcs {
			for _, f := range funcs {
				vname := xVar(b.ID, f.ID)
				if strings.Contains(line, vname) {
					fields := strings.Fields(line)
					for i, field := range fields {
						if field == vname && i+1 < len(fields) {
							val, _ := strconv.ParseFloat(fields[i+1], 64)
							if val > 0.5 {
								groupsMap[b.ID] = append(groupsMap[b.ID], f.ID)
							}
						}
					}
				}
			}
		}
	}

	// Convert to []*LambdaFunction groups, only including groups where x[b,b]=1.
	var groups [][]*domain.LambdaFunction
	for bID, memberIDs := range groupsMap {
		// Only include if b is actually a root (x[b,b]=1 is implied by presence in map).
		isRoot := false
		for _, mid := range memberIDs {
			if mid == bID {
				isRoot = true
				break
			}
		}
		if !isRoot {
			continue
		}
		group := make([]*domain.LambdaFunction, 0, len(memberIDs))
		for _, fid := range memberIDs {
			if f, ok := fm[fid]; ok {
				group = append(group, f)
			}
		}
		if len(group) > 0 {
			groups = append(groups, group)
		}
	}

	return &Result{Optimal: true, Status: "OPTIMAL", Groups: groups}, nil
}

// sanitize replaces characters that are invalid in LP variable names.
func sanitize(s string) string {
	replacer := strings.NewReplacer("-", "_", ".", "_", " ", "_", "/", "_")
	return replacer.Replace(s)
}
