// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/graph.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Corresponds to LambdaFunction in structures.py.
// Fields are split into two groups:
//   - Static: sourced from serverless.yml by the parser service
//   - Telemetry: filled in by the enricher service (zero value = not yet enriched)
type FunctionNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Static fields (from YAML) ──────────────────────────────────────────────
	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                    // unique key within the application, e.g. "resize"
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // human-readable, same as id for now
	MemoryMb    int32             `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`       // memorySize from YAML or provider default
	TimeoutSec  int32             `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"` // timeout in seconds
	Handler     string            `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`                          // e.g. "src/resize.handler"
	Runtime     string            `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`                          // e.g. "nodejs18.x"
	Environment map[string]string `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// data_out_bytes: maps child function ID → bytes transferred on that edge
	// Corresponds to LambdaFunction.data_out_edges in structures.py
	DataOutBytes map[string]int64 `protobuf:"bytes,8,rep,name=data_out_bytes,json=dataOutBytes,proto3" json:"data_out_bytes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// load_factor: multiplier on baseline_runtime. Default 1.0.
	// Preserved from structures.py to support simulation mode.
	LoadFactor float64 `protobuf:"fixed64,9,opt,name=load_factor,json=loadFactor,proto3" json:"load_factor,omitempty"`
	// ── Telemetry fields (from enricher / CloudWatch) ─────────────────────────
	// Zero value means "not yet enriched" — all algorithms must handle this gracefully.
	AvgDurationMs   float64 `protobuf:"fixed64,20,opt,name=avg_duration_ms,json=avgDurationMs,proto3" json:"avg_duration_ms,omitempty"`
	AvgMemoryUsedMb float64 `protobuf:"fixed64,21,opt,name=avg_memory_used_mb,json=avgMemoryUsedMb,proto3" json:"avg_memory_used_mb,omitempty"`
	InvocationCount int64   `protobuf:"varint,22,opt,name=invocation_count,json=invocationCount,proto3" json:"invocation_count,omitempty"`
	ErrorRate       float64 `protobuf:"fixed64,23,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	P99LatencyMs    float64 `protobuf:"fixed64,24,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	ColdStartRate   float64 `protobuf:"fixed64,25,opt,name=cold_start_rate,json=coldStartRate,proto3" json:"cold_start_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FunctionNode) Reset() {
	*x = FunctionNode{}
	mi := &file_proto_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionNode) ProtoMessage() {}

func (x *FunctionNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionNode.ProtoReflect.Descriptor instead.
func (*FunctionNode) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionNode) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *FunctionNode) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *FunctionNode) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *FunctionNode) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *FunctionNode) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *FunctionNode) GetDataOutBytes() map[string]int64 {
	if x != nil {
		return x.DataOutBytes
	}
	return nil
}

func (x *FunctionNode) GetLoadFactor() float64 {
	if x != nil {
		return x.LoadFactor
	}
	return 0
}

func (x *FunctionNode) GetAvgDurationMs() float64 {
	if x != nil {
		return x.AvgDurationMs
	}
	return 0
}

func (x *FunctionNode) GetAvgMemoryUsedMb() float64 {
	if x != nil {
		return x.AvgMemoryUsedMb
	}
	return 0
}

func (x *FunctionNode) GetInvocationCount() int64 {
	if x != nil {
		return x.InvocationCount
	}
	return 0
}

func (x *FunctionNode) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *FunctionNode) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *FunctionNode) GetColdStartRate() float64 {
	if x != nil {
		return x.ColdStartRate
	}
	return 0
}

// Directed edge between two function nodes.
// The weight is the data transfer cost in USD (pre-computed from data_out_bytes).
// Kept separate from FunctionNode.data_out_bytes so graph algorithms can
// work with a simple edge list without dereferencing node maps.
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`                             // parent function ID
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`                                 // child function ID
	DataBytes     int64                  `protobuf:"varint,3,opt,name=data_bytes,json=dataBytes,proto3" json:"data_bytes,omitempty"` // raw bytes transferred
	CostUsd       float64                `protobuf:"fixed64,4,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`      // (data_bytes / GiB) * $0.01 — pre-computed by parser
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_proto_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Edge) GetDataBytes() int64 {
	if x != nil {
		return x.DataBytes
	}
	return 0
}

func (x *Edge) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

// Constraints on the application — from the custom.optifuse block in serverless.yml.
// Corresponds to the constraint fields on Application in structures.py.
type Constraints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxMemoryMb   int32                  `protobuf:"varint,1,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`    // default 1024
	MaxLatencyMs  int32                  `protobuf:"varint,2,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"` // default 30000
	NetworkHopMs  int32                  `protobuf:"varint,3,opt,name=network_hop_ms,json=networkHopMs,proto3" json:"network_hop_ms,omitempty"` // default 20 — latency added per cross-group call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraints) Reset() {
	*x = Constraints{}
	mi := &file_proto_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraints) ProtoMessage() {}

func (x *Constraints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraints.ProtoReflect.Descriptor instead.
func (*Constraints) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Constraints) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *Constraints) GetMaxLatencyMs() int32 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *Constraints) GetNetworkHopMs() int32 {
	if x != nil {
		return x.NetworkHopMs
	}
	return 0
}

// The full application graph.
// Corresponds to Application in structures.py.
type Graph struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nodes         map[string]*FunctionNode `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // keyed by function ID
	Edges         []*Edge                  `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	CriticalPath  []string                 `protobuf:"bytes,4,rep,name=critical_path,json=criticalPath,proto3" json:"critical_path,omitempty"` // ordered list of function IDs
	Constraints   *Constraints             `protobuf:"bytes,5,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_proto_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{3}
}

func (x *Graph) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Graph) GetNodes() map[string]*FunctionNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Graph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Graph) GetCriticalPath() []string {
	if x != nil {
		return x.CriticalPath
	}
	return nil
}

func (x *Graph) GetConstraints() *Constraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

var File_proto_graph_proto protoreflect.FileDescriptor

const file_proto_graph_proto_rawDesc = "" +
	"\n" +
	"\x11proto/graph.proto\x12\x11optifuse.graph.v1\"\xe0\x05\n" +
	"\fFunctionNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\x12\x1f\n" +
	"\vtimeout_sec\x18\x04 \x01(\x05R\n" +
	"timeoutSec\x12\x18\n" +
	"\ahandler\x18\x05 \x01(\tR\ahandler\x12\x18\n" +
	"\aruntime\x18\x06 \x01(\tR\aruntime\x12R\n" +
	"\venvironment\x18\a \x03(\v20.optifuse.graph.v1.FunctionNode.EnvironmentEntryR\venvironment\x12W\n" +
	"\x0edata_out_bytes\x18\b \x03(\v21.optifuse.graph.v1.FunctionNode.DataOutBytesEntryR\fdataOutBytes\x12\x1f\n" +
	"\vload_factor\x18\t \x01(\x01R\n" +
	"loadFactor\x12&\n" +
	"\x0favg_duration_ms\x18\x14 \x01(\x01R\ravgDurationMs\x12+\n" +
	"\x12avg_memory_used_mb\x18\x15 \x01(\x01R\x0favgMemoryUsedMb\x12)\n" +
	"\x10invocation_count\x18\x16 \x01(\x03R\x0finvocationCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x17 \x01(\x01R\terrorRate\x12$\n" +
	"\x0ep99_latency_ms\x18\x18 \x01(\x01R\fp99LatencyMs\x12&\n" +
	"\x0fcold_start_rate\x18\x19 \x01(\x01R\rcoldStartRate\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11DataOutBytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"d\n" +
	"\x04Edge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"data_bytes\x18\x03 \x01(\x03R\tdataBytes\x12\x19\n" +
	"\bcost_usd\x18\x04 \x01(\x01R\acostUsd\"}\n" +
	"\vConstraints\x12\"\n" +
	"\rmax_memory_mb\x18\x01 \x01(\x05R\vmaxMemoryMb\x12$\n" +
	"\x0emax_latency_ms\x18\x02 \x01(\x05R\fmaxLatencyMs\x12$\n" +
	"\x0enetwork_hop_ms\x18\x03 \x01(\x05R\fnetworkHopMs\"\xc7\x02\n" +
	"\x05Graph\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x05nodes\x18\x02 \x03(\v2#.optifuse.graph.v1.Graph.NodesEntryR\x05nodes\x12-\n" +
	"\x05edges\x18\x03 \x03(\v2\x17.optifuse.graph.v1.EdgeR\x05edges\x12#\n" +
	"\rcritical_path\x18\x04 \x03(\tR\fcriticalPath\x12@\n" +
	"\vconstraints\x18\x05 \x01(\v2\x1e.optifuse.graph.v1.ConstraintsR\vconstraints\x1aY\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.optifuse.graph.v1.FunctionNodeR\x05value:\x028\x01B2Z0github.com/Vaivaswat2244/OptiFuse_go/proto;protob\x06proto3"

var (
	file_proto_graph_proto_rawDescOnce sync.Once
	file_proto_graph_proto_rawDescData []byte
)

func file_proto_graph_proto_rawDescGZIP() []byte {
	file_proto_graph_proto_rawDescOnce.Do(func() {
		file_proto_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)))
	})
	return file_proto_graph_proto_rawDescData
}

var file_proto_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_graph_proto_goTypes = []any{
	(*FunctionNode)(nil), // 0: optifuse.graph.v1.FunctionNode
	(*Edge)(nil),         // 1: optifuse.graph.v1.Edge
	(*Constraints)(nil),  // 2: optifuse.graph.v1.Constraints
	(*Graph)(nil),        // 3: optifuse.graph.v1.Graph
	nil,                  // 4: optifuse.graph.v1.FunctionNode.EnvironmentEntry
	nil,                  // 5: optifuse.graph.v1.FunctionNode.DataOutBytesEntry
	nil,                  // 6: optifuse.graph.v1.Graph.NodesEntry
}
var file_proto_graph_proto_depIdxs = []int32{
	4, // 0: optifuse.graph.v1.FunctionNode.environment:type_name -> optifuse.graph.v1.FunctionNode.EnvironmentEntry
	5, // 1: optifuse.graph.v1.FunctionNode.data_out_bytes:type_name -> optifuse.graph.v1.FunctionNode.DataOutBytesEntry
	6, // 2: optifuse.graph.v1.Graph.nodes:type_name -> optifuse.graph.v1.Graph.NodesEntry
	1, // 3: optifuse.graph.v1.Graph.edges:type_name -> optifuse.graph.v1.Edge
	2, // 4: optifuse.graph.v1.Graph.constraints:type_name -> optifuse.graph.v1.Constraints
	0, // 5: optifuse.graph.v1.Graph.NodesEntry.value:type_name -> optifuse.graph.v1.FunctionNode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_graph_proto_init() }
func file_proto_graph_proto_init() {
	if File_proto_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_graph_proto_goTypes,
		DependencyIndexes: file_proto_graph_proto_depIdxs,
		MessageInfos:      file_proto_graph_proto_msgTypes,
	}.Build()
	File_proto_graph_proto = out.File
	file_proto_graph_proto_goTypes = nil
	file_proto_graph_proto_depIdxs = nil
}
