// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/optimizer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Which algorithm(s) to run. Matches the 5 Python implementations exactly.
type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED  Algorithm = 0
	Algorithm_ALGORITHM_NO_FUSION    Algorithm = 1 // no_fusion      — baseline, each func is its own group
	Algorithm_ALGORITHM_SINGLETON    Algorithm = 2 // singleton      — all funcs in one group (BFS order)
	Algorithm_ALGORITHM_MIN_W_CUT    Algorithm = 3 // min_w_cut_heuristic
	Algorithm_ALGORITHM_GREEDY_TP    Algorithm = 4 // greedy_tree_partitioning
	Algorithm_ALGORITHM_COSTLESS_CSP Algorithm = 5 // costless_csp   — Pareto-optimal label-setting on critical path
	Algorithm_ALGORITHM_MTX_ILP      Algorithm = 6 // mtx_ilp        — optimal ILP (slow, use with caution)
	Algorithm_ALGORITHM_ALL          Algorithm = 7 // run all 6 and return all results
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_NO_FUSION",
		2: "ALGORITHM_SINGLETON",
		3: "ALGORITHM_MIN_W_CUT",
		4: "ALGORITHM_GREEDY_TP",
		5: "ALGORITHM_COSTLESS_CSP",
		6: "ALGORITHM_MTX_ILP",
		7: "ALGORITHM_ALL",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED":  0,
		"ALGORITHM_NO_FUSION":    1,
		"ALGORITHM_SINGLETON":    2,
		"ALGORITHM_MIN_W_CUT":    3,
		"ALGORITHM_GREEDY_TP":    4,
		"ALGORITHM_COSTLESS_CSP": 5,
		"ALGORITHM_MTX_ILP":      6,
		"ALGORITHM_ALL":          7,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_optimizer_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_proto_optimizer_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_proto_optimizer_proto_rawDescGZIP(), []int{0}
}

// A single fused deployment group — corresponds to CompositeFunction in structures.py.
// Contains the IDs of all member functions, plus pre-computed aggregate metrics.
type FusionGroup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FunctionIds      []string               `protobuf:"bytes,1,rep,name=function_ids,json=functionIds,proto3" json:"function_ids,omitempty"`                    // ordered; first ID is the group's canonical ID
	TotalMemoryMb    int32                  `protobuf:"varint,2,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`           // sum of member memory
	TotalRuntimeMs   int32                  `protobuf:"varint,3,opt,name=total_runtime_ms,json=totalRuntimeMs,proto3" json:"total_runtime_ms,omitempty"`        // sum of member runtimes (sequential execution)
	ExecutionCostUsd float64                `protobuf:"fixed64,4,opt,name=execution_cost_usd,json=executionCostUsd,proto3" json:"execution_cost_usd,omitempty"` // (total_memory_mb/1024) * (total_runtime_ms/1000) * 0.00001667
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FusionGroup) Reset() {
	*x = FusionGroup{}
	mi := &file_proto_optimizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FusionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FusionGroup) ProtoMessage() {}

func (x *FusionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_optimizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FusionGroup.ProtoReflect.Descriptor instead.
func (*FusionGroup) Descriptor() ([]byte, []int) {
	return file_proto_optimizer_proto_rawDescGZIP(), []int{0}
}

func (x *FusionGroup) GetFunctionIds() []string {
	if x != nil {
		return x.FunctionIds
	}
	return nil
}

func (x *FusionGroup) GetTotalMemoryMb() int32 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *FusionGroup) GetTotalRuntimeMs() int32 {
	if x != nil {
		return x.TotalRuntimeMs
	}
	return 0
}

func (x *FusionGroup) GetExecutionCostUsd() float64 {
	if x != nil {
		return x.ExecutionCostUsd
	}
	return 0
}

// Metrics for a complete partition — corresponds to calculate_metrics() output.
type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCostUsd  float64                `protobuf:"fixed64,1,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"` // execution cost + data transfer cost across all cut edges
	LatencyMs     float64                `protobuf:"fixed64,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`            // critical path latency including network hops at cuts
	Feasible      bool                   `protobuf:"varint,3,opt,name=feasible,proto3" json:"feasible,omitempty"`                                // true iff memory and latency constraints are satisfied
	RuntimeMs     float64                `protobuf:"fixed64,4,opt,name=runtime_ms,json=runtimeMs,proto3" json:"runtime_ms,omitempty"`            // wall-clock time the algorithm itself took
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_optimizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_optimizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_optimizer_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

func (x *Metrics) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Metrics) GetFeasible() bool {
	if x != nil {
		return x.Feasible
	}
	return false
}

func (x *Metrics) GetRuntimeMs() float64 {
	if x != nil {
		return x.RuntimeMs
	}
	return 0
}

// Result from a single algorithm run.
type AlgorithmResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // human-readable algo name, e.g. "Greedy TP (GrTP)"
	Algorithm     Algorithm              `protobuf:"varint,2,opt,name=algorithm,proto3,enum=optifuse.optimizer.v1.Algorithm" json:"algorithm,omitempty"`
	Groups        []*FusionGroup         `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error         bool                   `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmResult) Reset() {
	*x = AlgorithmResult{}
	mi := &file_proto_optimizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmResult) ProtoMessage() {}

func (x *AlgorithmResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_optimizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmResult.ProtoReflect.Descriptor instead.
func (*AlgorithmResult) Descriptor() ([]byte, []int) {
	return file_proto_optimizer_proto_rawDescGZIP(), []int{2}
}

func (x *AlgorithmResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlgorithmResult) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *AlgorithmResult) GetGroups() []*FusionGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *AlgorithmResult) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AlgorithmResult) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *AlgorithmResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// The full optimization plan returned by the optimizer service.
// Contains results from all requested algorithms so the frontend
// can display a comparison table.
type OptimizationPlan struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Results []*AlgorithmResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// The recommended result — lowest cost among feasible solutions.
	// Empty if no feasible solution was found.
	Recommended   *AlgorithmResult `protobuf:"bytes,2,opt,name=recommended,proto3" json:"recommended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizationPlan) Reset() {
	*x = OptimizationPlan{}
	mi := &file_proto_optimizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationPlan) ProtoMessage() {}

func (x *OptimizationPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_optimizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationPlan.ProtoReflect.Descriptor instead.
func (*OptimizationPlan) Descriptor() ([]byte, []int) {
	return file_proto_optimizer_proto_rawDescGZIP(), []int{3}
}

func (x *OptimizationPlan) GetResults() []*AlgorithmResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *OptimizationPlan) GetRecommended() *AlgorithmResult {
	if x != nil {
		return x.Recommended
	}
	return nil
}

type OptimizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graph         *Graph                 `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	Algorithms    []Algorithm            `protobuf:"varint,2,rep,packed,name=algorithms,proto3,enum=optifuse.optimizer.v1.Algorithm" json:"algorithms,omitempty"` // if empty, runs ALGORITHM_ALL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_proto_optimizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_optimizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_optimizer_proto_rawDescGZIP(), []int{4}
}

func (x *OptimizeRequest) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *OptimizeRequest) GetAlgorithms() []Algorithm {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

type OptimizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *OptimizationPlan      `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_proto_optimizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_optimizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_optimizer_proto_rawDescGZIP(), []int{5}
}

func (x *OptimizeResponse) GetPlan() *OptimizationPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

var File_proto_optimizer_proto protoreflect.FileDescriptor

const file_proto_optimizer_proto_rawDesc = "" +
	"\n" +
	"\x15proto/optimizer.proto\x12\x15optifuse.optimizer.v1\x1a\x11proto/graph.proto\"\xb0\x01\n" +
	"\vFusionGroup\x12!\n" +
	"\ffunction_ids\x18\x01 \x03(\tR\vfunctionIds\x12&\n" +
	"\x0ftotal_memory_mb\x18\x02 \x01(\x05R\rtotalMemoryMb\x12(\n" +
	"\x10total_runtime_ms\x18\x03 \x01(\x05R\x0etotalRuntimeMs\x12,\n" +
	"\x12execution_cost_usd\x18\x04 \x01(\x01R\x10executionCostUsd\"\x89\x01\n" +
	"\aMetrics\x12$\n" +
	"\x0etotal_cost_usd\x18\x01 \x01(\x01R\ftotalCostUsd\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x01R\tlatencyMs\x12\x1a\n" +
	"\bfeasible\x18\x03 \x01(\bR\bfeasible\x12\x1d\n" +
	"\n" +
	"runtime_ms\x18\x04 \x01(\x01R\truntimeMs\"\x96\x02\n" +
	"\x0fAlgorithmResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\talgorithm\x18\x02 \x01(\x0e2 .optifuse.optimizer.v1.AlgorithmR\talgorithm\x12:\n" +
	"\x06groups\x18\x03 \x03(\v2\".optifuse.optimizer.v1.FusionGroupR\x06groups\x128\n" +
	"\ametrics\x18\x04 \x01(\v2\x1e.optifuse.optimizer.v1.MetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\x05 \x01(\bR\x05error\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x9e\x01\n" +
	"\x10OptimizationPlan\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.optifuse.optimizer.v1.AlgorithmResultR\aresults\x12H\n" +
	"\vrecommended\x18\x02 \x01(\v2&.optifuse.optimizer.v1.AlgorithmResultR\vrecommended\"\x83\x01\n" +
	"\x0fOptimizeRequest\x12.\n" +
	"\x05graph\x18\x01 \x01(\v2\x18.optifuse.graph.v1.GraphR\x05graph\x12@\n" +
	"\n" +
	"algorithms\x18\x02 \x03(\x0e2 .optifuse.optimizer.v1.AlgorithmR\n" +
	"algorithms\"O\n" +
	"\x10OptimizeResponse\x12;\n" +
	"\x04plan\x18\x01 \x01(\v2'.optifuse.optimizer.v1.OptimizationPlanR\x04plan*\xd0\x01\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ALGORITHM_NO_FUSION\x10\x01\x12\x17\n" +
	"\x13ALGORITHM_SINGLETON\x10\x02\x12\x17\n" +
	"\x13ALGORITHM_MIN_W_CUT\x10\x03\x12\x17\n" +
	"\x13ALGORITHM_GREEDY_TP\x10\x04\x12\x1a\n" +
	"\x16ALGORITHM_COSTLESS_CSP\x10\x05\x12\x15\n" +
	"\x11ALGORITHM_MTX_ILP\x10\x06\x12\x11\n" +
	"\rALGORITHM_ALL\x10\a2o\n" +
	"\x10OptimizerService\x12[\n" +
	"\bOptimize\x12&.optifuse.optimizer.v1.OptimizeRequest\x1a'.optifuse.optimizer.v1.OptimizeResponseB2Z0github.com/Vaivaswat2244/OptiFuse_go/proto;protob\x06proto3"

var (
	file_proto_optimizer_proto_rawDescOnce sync.Once
	file_proto_optimizer_proto_rawDescData []byte
)

func file_proto_optimizer_proto_rawDescGZIP() []byte {
	file_proto_optimizer_proto_rawDescOnce.Do(func() {
		file_proto_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_optimizer_proto_rawDesc), len(file_proto_optimizer_proto_rawDesc)))
	})
	return file_proto_optimizer_proto_rawDescData
}

var file_proto_optimizer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_optimizer_proto_goTypes = []any{
	(Algorithm)(0),           // 0: optifuse.optimizer.v1.Algorithm
	(*FusionGroup)(nil),      // 1: optifuse.optimizer.v1.FusionGroup
	(*Metrics)(nil),          // 2: optifuse.optimizer.v1.Metrics
	(*AlgorithmResult)(nil),  // 3: optifuse.optimizer.v1.AlgorithmResult
	(*OptimizationPlan)(nil), // 4: optifuse.optimizer.v1.OptimizationPlan
	(*OptimizeRequest)(nil),  // 5: optifuse.optimizer.v1.OptimizeRequest
	(*OptimizeResponse)(nil), // 6: optifuse.optimizer.v1.OptimizeResponse
	(*Graph)(nil),            // 7: optifuse.graph.v1.Graph
}
var file_proto_optimizer_proto_depIdxs = []int32{
	0, // 0: optifuse.optimizer.v1.AlgorithmResult.algorithm:type_name -> optifuse.optimizer.v1.Algorithm
	1, // 1: optifuse.optimizer.v1.AlgorithmResult.groups:type_name -> optifuse.optimizer.v1.FusionGroup
	2, // 2: optifuse.optimizer.v1.AlgorithmResult.metrics:type_name -> optifuse.optimizer.v1.Metrics
	3, // 3: optifuse.optimizer.v1.OptimizationPlan.results:type_name -> optifuse.optimizer.v1.AlgorithmResult
	3, // 4: optifuse.optimizer.v1.OptimizationPlan.recommended:type_name -> optifuse.optimizer.v1.AlgorithmResult
	7, // 5: optifuse.optimizer.v1.OptimizeRequest.graph:type_name -> optifuse.graph.v1.Graph
	0, // 6: optifuse.optimizer.v1.OptimizeRequest.algorithms:type_name -> optifuse.optimizer.v1.Algorithm
	4, // 7: optifuse.optimizer.v1.OptimizeResponse.plan:type_name -> optifuse.optimizer.v1.OptimizationPlan
	5, // 8: optifuse.optimizer.v1.OptimizerService.Optimize:input_type -> optifuse.optimizer.v1.OptimizeRequest
	6, // 9: optifuse.optimizer.v1.OptimizerService.Optimize:output_type -> optifuse.optimizer.v1.OptimizeResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_optimizer_proto_init() }
func file_proto_optimizer_proto_init() {
	if File_proto_optimizer_proto != nil {
		return
	}
	file_proto_graph_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_optimizer_proto_rawDesc), len(file_proto_optimizer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_optimizer_proto_goTypes,
		DependencyIndexes: file_proto_optimizer_proto_depIdxs,
		EnumInfos:         file_proto_optimizer_proto_enumTypes,
		MessageInfos:      file_proto_optimizer_proto_msgTypes,
	}.Build()
	File_proto_optimizer_proto = out.File
	file_proto_optimizer_proto_goTypes = nil
	file_proto_optimizer_proto_depIdxs = nil
}
