// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/services.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoName      string                 `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	YamlContent   []byte                 `protobuf:"bytes,2,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"` // raw serverless.yml bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_proto_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *ParseRequest) GetYamlContent() []byte {
	if x != nil {
		return x.YamlContent
	}
	return nil
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graph         *Graph                 `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"` // non-fatal issues (e.g. missing topology block)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_proto_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *ParseResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type EnrichRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Graph *Graph                 `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	// AWS assume-role parameters — corresponds to get_assumed_role_session() in aws.py
	RoleArn    string `protobuf:"bytes,2,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"` // e.g. "arn:aws:iam::123456789012:role/OptifuseReader"
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Serverless Framework deployment identifiers — needed to build log group names:
	// /aws/lambda/{service_name}-{stage}-{function_id}
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Stage       string `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	// How far back to query. Defaults to 24h if zero.
	LookbackHours int32 `protobuf:"varint,6,opt,name=lookback_hours,json=lookbackHours,proto3" json:"lookback_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichRequest) Reset() {
	*x = EnrichRequest{}
	mi := &file_proto_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichRequest) ProtoMessage() {}

func (x *EnrichRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichRequest.ProtoReflect.Descriptor instead.
func (*EnrichRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichRequest) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *EnrichRequest) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *EnrichRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *EnrichRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *EnrichRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *EnrichRequest) GetLookbackHours() int32 {
	if x != nil {
		return x.LookbackHours
	}
	return 0
}

type EnrichResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graph         *Graph                 `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`                                // same graph, telemetry fields now populated
	EnrichedIds   []string               `protobuf:"bytes,2,rep,name=enriched_ids,json=enrichedIds,proto3" json:"enriched_ids,omitempty"` // function IDs that had CloudWatch data
	MissingIds    []string               `protobuf:"bytes,3,rep,name=missing_ids,json=missingIds,proto3" json:"missing_ids,omitempty"`    // function IDs with no log data found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichResponse) Reset() {
	*x = EnrichResponse{}
	mi := &file_proto_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichResponse) ProtoMessage() {}

func (x *EnrichResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichResponse.ProtoReflect.Descriptor instead.
func (*EnrichResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{3}
}

func (x *EnrichResponse) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *EnrichResponse) GetEnrichedIds() []string {
	if x != nil {
		return x.EnrichedIds
	}
	return nil
}

func (x *EnrichResponse) GetMissingIds() []string {
	if x != nil {
		return x.MissingIds
	}
	return nil
}

type DeployRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OriginalYamlContent []byte                 `protobuf:"bytes,1,opt,name=original_yaml_content,json=originalYamlContent,proto3" json:"original_yaml_content,omitempty"` // the original serverless.yml bytes
	Result              *AlgorithmResult       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                                                        // the chosen fusion plan
	// AWS credentials for deployment
	RoleArn    string `protobuf:"bytes,3,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	ExternalId string `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Region     string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	// If false: only generate the optimized YAML, don't actually deploy.
	// If true: generate + run `serverless deploy`.
	DeployLive    bool `protobuf:"varint,6,opt,name=deploy_live,json=deployLive,proto3" json:"deploy_live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_proto_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{4}
}

func (x *DeployRequest) GetOriginalYamlContent() []byte {
	if x != nil {
		return x.OriginalYamlContent
	}
	return nil
}

func (x *DeployRequest) GetResult() *AlgorithmResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DeployRequest) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *DeployRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DeployRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DeployRequest) GetDeployLive() bool {
	if x != nil {
		return x.DeployLive
	}
	return false
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptimizedYaml []byte                 `protobuf:"bytes,1,opt,name=optimized_yaml,json=optimizedYaml,proto3" json:"optimized_yaml,omitempty"` // the generated serverless.yml bytes
	Deployed      bool                   `protobuf:"varint,2,opt,name=deployed,proto3" json:"deployed,omitempty"`                               // true if deploy_live was true and succeeded
	DeployLog     string                 `protobuf:"bytes,3,opt,name=deploy_log,json=deployLog,proto3" json:"deploy_log,omitempty"`             // stdout/stderr from the deploy command
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_proto_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_proto_rawDescGZIP(), []int{5}
}

func (x *DeployResponse) GetOptimizedYaml() []byte {
	if x != nil {
		return x.OptimizedYaml
	}
	return nil
}

func (x *DeployResponse) GetDeployed() bool {
	if x != nil {
		return x.Deployed
	}
	return false
}

func (x *DeployResponse) GetDeployLog() string {
	if x != nil {
		return x.DeployLog
	}
	return ""
}

func (x *DeployResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_services_proto protoreflect.FileDescriptor

const file_proto_services_proto_rawDesc = "" +
	"\n" +
	"\x14proto/services.proto\x12\x14optifuse.services.v1\x1a\x11proto/graph.proto\x1a\x15proto/optimizer.proto\"N\n" +
	"\fParseRequest\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12!\n" +
	"\fyaml_content\x18\x02 \x01(\fR\vyamlContent\"[\n" +
	"\rParseResponse\x12.\n" +
	"\x05graph\x18\x01 \x01(\v2\x18.optifuse.graph.v1.GraphR\x05graph\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\"\xdb\x01\n" +
	"\rEnrichRequest\x12.\n" +
	"\x05graph\x18\x01 \x01(\v2\x18.optifuse.graph.v1.GraphR\x05graph\x12\x19\n" +
	"\brole_arn\x18\x02 \x01(\tR\aroleArn\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\x12%\n" +
	"\x0elookback_hours\x18\x06 \x01(\x05R\rlookbackHours\"\x84\x01\n" +
	"\x0eEnrichResponse\x12.\n" +
	"\x05graph\x18\x01 \x01(\v2\x18.optifuse.graph.v1.GraphR\x05graph\x12!\n" +
	"\fenriched_ids\x18\x02 \x03(\tR\venrichedIds\x12\x1f\n" +
	"\vmissing_ids\x18\x03 \x03(\tR\n" +
	"missingIds\"\xf8\x01\n" +
	"\rDeployRequest\x122\n" +
	"\x15original_yaml_content\x18\x01 \x01(\fR\x13originalYamlContent\x12>\n" +
	"\x06result\x18\x02 \x01(\v2&.optifuse.optimizer.v1.AlgorithmResultR\x06result\x12\x19\n" +
	"\brole_arn\x18\x03 \x01(\tR\aroleArn\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vdeploy_live\x18\x06 \x01(\bR\n" +
	"deployLive\"\x88\x01\n" +
	"\x0eDeployResponse\x12%\n" +
	"\x0eoptimized_yaml\x18\x01 \x01(\fR\roptimizedYaml\x12\x1a\n" +
	"\bdeployed\x18\x02 \x01(\bR\bdeployed\x12\x1d\n" +
	"\n" +
	"deploy_log\x18\x03 \x01(\tR\tdeployLog\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2a\n" +
	"\rParserService\x12P\n" +
	"\x05Parse\x12\".optifuse.services.v1.ParseRequest\x1a#.optifuse.services.v1.ParseResponse2f\n" +
	"\x0fEnricherService\x12S\n" +
	"\x06Enrich\x12#.optifuse.services.v1.EnrichRequest\x1a$.optifuse.services.v1.EnrichResponse2f\n" +
	"\x0fDeployerService\x12S\n" +
	"\x06Deploy\x12#.optifuse.services.v1.DeployRequest\x1a$.optifuse.services.v1.DeployResponseB2Z0github.com/Vaivaswat2244/OptiFuse_go/proto;protob\x06proto3"

var (
	file_proto_services_proto_rawDescOnce sync.Once
	file_proto_services_proto_rawDescData []byte
)

func file_proto_services_proto_rawDescGZIP() []byte {
	file_proto_services_proto_rawDescOnce.Do(func() {
		file_proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_proto_rawDesc), len(file_proto_services_proto_rawDesc)))
	})
	return file_proto_services_proto_rawDescData
}

var file_proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_services_proto_goTypes = []any{
	(*ParseRequest)(nil),    // 0: optifuse.services.v1.ParseRequest
	(*ParseResponse)(nil),   // 1: optifuse.services.v1.ParseResponse
	(*EnrichRequest)(nil),   // 2: optifuse.services.v1.EnrichRequest
	(*EnrichResponse)(nil),  // 3: optifuse.services.v1.EnrichResponse
	(*DeployRequest)(nil),   // 4: optifuse.services.v1.DeployRequest
	(*DeployResponse)(nil),  // 5: optifuse.services.v1.DeployResponse
	(*Graph)(nil),           // 6: optifuse.graph.v1.Graph
	(*AlgorithmResult)(nil), // 7: optifuse.optimizer.v1.AlgorithmResult
}
var file_proto_services_proto_depIdxs = []int32{
	6, // 0: optifuse.services.v1.ParseResponse.graph:type_name -> optifuse.graph.v1.Graph
	6, // 1: optifuse.services.v1.EnrichRequest.graph:type_name -> optifuse.graph.v1.Graph
	6, // 2: optifuse.services.v1.EnrichResponse.graph:type_name -> optifuse.graph.v1.Graph
	7, // 3: optifuse.services.v1.DeployRequest.result:type_name -> optifuse.optimizer.v1.AlgorithmResult
	0, // 4: optifuse.services.v1.ParserService.Parse:input_type -> optifuse.services.v1.ParseRequest
	2, // 5: optifuse.services.v1.EnricherService.Enrich:input_type -> optifuse.services.v1.EnrichRequest
	4, // 6: optifuse.services.v1.DeployerService.Deploy:input_type -> optifuse.services.v1.DeployRequest
	1, // 7: optifuse.services.v1.ParserService.Parse:output_type -> optifuse.services.v1.ParseResponse
	3, // 8: optifuse.services.v1.EnricherService.Enrich:output_type -> optifuse.services.v1.EnrichResponse
	5, // 9: optifuse.services.v1.DeployerService.Deploy:output_type -> optifuse.services.v1.DeployResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_services_proto_init() }
func file_proto_services_proto_init() {
	if File_proto_services_proto != nil {
		return
	}
	file_proto_graph_proto_init()
	file_proto_optimizer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_proto_rawDesc), len(file_proto_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_services_proto_goTypes,
		DependencyIndexes: file_proto_services_proto_depIdxs,
		MessageInfos:      file_proto_services_proto_msgTypes,
	}.Build()
	File_proto_services_proto = out.File
	file_proto_services_proto_goTypes = nil
	file_proto_services_proto_depIdxs = nil
}
